// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAld9Xib_K5kqABB2m4c_6LfS1vUFZVWU0',
    appId: '1:715846110086:web:25bd3d7a13c9421f653a07',
    messagingSenderId: '715846110086',
    projectId: 'evidence-system-6f225',
    authDomain: 'evidence-system-6f225.firebaseapp.com',
    storageBucket: 'evidence-system-6f225.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGnlADvalHJHdFvtqPy-8bQd4OS5qqc-U',
    appId: '1:715846110086:android:de4efb14fc51cc78653a07',
    messagingSenderId: '715846110086',
    projectId: 'evidence-system-6f225',
    storageBucket: 'evidence-system-6f225.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAld9Xib_K5kqABB2m4c_6LfS1vUFZVWU0',
    appId: '1:715846110086:web:04d0fbd9a3d243f3653a07',
    messagingSenderId: '715846110086',
    projectId: 'evidence-system-6f225',
    authDomain: 'evidence-system-6f225.firebaseapp.com',
    storageBucket: 'evidence-system-6f225.firebasestorage.app',
  );
}
